
################################################################################################################################################
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: #
#                                                                                                                                              #
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                                                                                       #
#                                                                                                                                              #
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.           #
################################################################################################################################################

counter = 0

fib_list = [1, 2, 3]

for i in range (2, 4000000):
    n = fib_list[-1] + fib_list[-2]
    if n > 4000000:
        break
    fib_list.append(n)
    if n%2 == 0:
        counter += n

print(fib_list)
print(counter)  # add 2 to get the right answer, this is because 2 already exists in fib_list and hasn't been accounted for
