################################################################################################
# How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100? #
################################################################################################

distinct = set()
for i in range(2, 101):
    for j in range(2, 101):
        distinct.add(i**j)

print(len(distinct))
